Increase the maximum heap size for builds on armhf
The flags for the Boot JDK Java command are '-Xms64M -Xmx768M' for big
workloads on armhf, while those same flags are '-Xms64M -Xmx2048M' on
the other architectures. Increase the maximum heap size to 2 GiB so that
it's the same across all architectures. Otherwise, builds on armhf fail
with the following messages:

  Generating JDK_API javadoc for 57 modules
  error: An internal exception has occurred.
  java.lang.OutOfMemoryError: Java heap space
    at java.base/java.lang.StringBuilder.toString(StringBuilder.java:478)
    at jdk.javadoc.interim/jdk.javadoc.internal.html.Entity.escapeHtmlChars(Entity.java:86)