Fix repeated error message on Raspberry Pi OS
Fix the repeated error message that occurs on the Raspberry Pi OS:

  ERROR: ld.so: object
  '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from
  /etc/ld.so.preload cannot be preloaded (cannot open shared object
  file): ignored.

(cherry picked from commit 412ffe3ccea4b6e7f6856c946d0a6405da44322a)